### ISSUE TITLE
[User Story] Emit AWS App hostname to .env

### ISSUE THREAD

**Issue by j4inam** [meetnearme/api#45]
As a developer, I need access to the dynamic AWS URL generated from the SST setup to use in the app for uses like building the redirect URL.

A.C.
 - Emit AWS hostname to .env
 - Replace all hardcoded uses of the hostname with the variable in .env

**Comment by brianfeister** [comment]
Likely not needed as context should be pulled from `request` as handled here

https://github.com/meetnearme/api/commit/421fd58ac875bb4346cbcb87f9ed91fe3c836ebf#diff-019ebe66f31368757e15573c1255b7a2e0403b52bf1e6170e6833ee64f491e10R35-R37
