### ISSUE TITLE
[bug] [seshu] Can confirm events even if all are invalid

### ISSUE THREAD

**Issue by Brandon-G-Tripp** [meetnearme/api#58]
The seshu UI allows confirmation of event data even if all events are marked as invalid. UI change needed to show no valid events were selected and to checkback end response if no events are selected as valid. 

<img width="1428" alt="Screen Shot 2024-07-13 at 5 28 51 PM" src="https://github.com/user-attachments/assets/cc5644a1-2461-4085-9bd2-b44b0b8c225e">

**Comment by brianfeister** [comment]
This is a bit of an odd scenario. If all events are invalid, what needs to happen is you need to actually either 

1. "Retry" the URL (hoping for a better LLM response)
2. Just give up (you might have provided the wrong URL, or one that actually has no events)

Given those scenarios, disabling the `Confirm Event Data` button doesn't really accomplish anything in the direction of resolving these problems.

How to do so gets **really ** complex

**Comment by brianfeister** [comment]
But I think it's fair to just disable the submit button and essentially communicate what I wrote above in the message next to the button
